// Copyright 2024-2026 Mazhai Technologies
// Licensed under the Apache License, Version 2.0
//
// WARNING: AUTO-GENERATED FILE — DO NOT EDIT
// Generated by build/encode_genesis.py at local
//
// This file contains PRODUCTION cryptographic material.
// It should be generated fresh per release in CI/CD and never committed.

#ifndef ARAN_GENESIS_PROD_H
#define ARAN_GENESIS_PROD_H

#include <cstdint>
#include <cstddef>

// ============================================================================
// Production Genesis State — Pre-computed XOR-chain Encoded Blobs
// ============================================================================

// AES-256 Key (32 bytes)
static const uint8_t _GENESIS_PROD_AES_KEY[32] = {
        0x87, 0x9F, 0x53, 0xE0, 0x32, 0xFC, 0x04, 0x10,
    0x0D, 0x6E, 0x9D, 0x0F, 0x49, 0x6E, 0xEE, 0xC7,
    0x6A, 0x68, 0xC0, 0xA6, 0xEE, 0x33, 0x06, 0xE8,
    0xD4, 0xFA, 0xB2, 0x32, 0x0C, 0x31, 0x00, 0xFE
};

// HMAC-SHA256 Secret (32 bytes)
static const uint8_t _GENESIS_PROD_HMAC_SECRET[32] = {
        0x9A, 0x21, 0xC1, 0x05, 0xCD, 0xA3, 0x64, 0x5C,
    0x50, 0xAF, 0xB6, 0xB6, 0x6F, 0x5A, 0x6B, 0x29,
    0x30, 0x6A, 0xC5, 0xE8, 0xB8, 0x53, 0x89, 0xDA,
    0x03, 0x00, 0x08, 0xEC, 0x54, 0xB0, 0x94, 0x3B
};

// Blinded TLS Pin 0 (32 bytes)
static const uint8_t _GENESIS_PROD_PIN0[32] = {
        0xFF, 0xA9, 0xF4, 0x96, 0x08, 0xA6, 0x3F, 0xCA,
    0x66, 0x04, 0xF6, 0xC6, 0x04, 0x88, 0xF8, 0xED,
    0x9F, 0xC4, 0x50, 0xA5, 0xB6, 0x75, 0x95, 0xBF,
    0x6D, 0x1F, 0x8F, 0x83, 0xDF, 0xE1, 0xB8, 0x02
};

// Blinded TLS Pin 1 (32 bytes)
static const uint8_t _GENESIS_PROD_PIN1[32] = {
        0x58, 0x88, 0x64, 0xB0, 0x4C, 0xEE, 0x6E, 0xB0,
    0x2E, 0x48, 0xE3, 0xC9, 0xAB, 0x2F, 0xDD, 0xFE,
    0x9B, 0x38, 0x66, 0x8B, 0xB0, 0x7E, 0x73, 0x6F,
    0x3D, 0x62, 0x34, 0x19, 0xE7, 0x41, 0x60, 0x01
};

// Blinding Salt (16 bytes)
static const uint8_t _GENESIS_PROD_SALT[16] = {
        0x8F, 0x5D, 0xBD, 0x0F, 0x1F, 0x75, 0x5C, 0x3E,
    0x6E, 0xF2, 0x06, 0x9D, 0x4C, 0xA1, 0xDB, 0x3B
};

// Sync Endpoint (null-terminated)
static const uint8_t _GENESIS_PROD_ENDPOINT[27] = {
        0xE4, 0x4F, 0x4B, 0xA4, 0xA1, 0x0F, 0x36, 0x34,
    0x53, 0x2E, 0x15, 0xF0, 0x59, 0x58, 0x8A, 0x28,
    0x34, 0x40, 0x96, 0xF0, 0x88, 0x8D, 0x94, 0x50,
    0xEE, 0x71, 0x51
};

// License Endpoint (null-terminated)
static const uint8_t _GENESIS_PROD_LICENSE_EP[51] = {
        0x5B, 0x0D, 0xE6, 0x76, 0x88, 0xF9, 0x3E, 0xCB,
    0x13, 0x93, 0x47, 0xDD, 0x8F, 0x51, 0x7D, 0x28,
    0x8B, 0x02, 0x3B, 0x22, 0xA1, 0x7B, 0x9C, 0xAF,
    0xAE, 0xCC, 0x03, 0x6E, 0x82, 0xCB, 0xD1, 0x9C,
    0xE6, 0x85, 0xD9, 0xB3, 0xDC, 0xE2, 0xCC, 0xFD,
    0x90, 0xBA, 0x68, 0x9C, 0x65, 0x78, 0xDC, 0x0F,
    0xDD, 0x89, 0x03
};

// Sync interval in seconds
static const uint32_t _GENESIS_PROD_SYNC_INTERVAL = 60;

// Default reaction policy (0=ignore, 1=alert, 2=block, 3=kill)
static const uint32_t _GENESIS_PROD_REACTION_POLICY = 3;  // KILL_APP

// ============================================================================
// Production State Loader (replaces runtime encoding)
// ============================================================================

static inline void aran_load_production_genesis(AranGenesisState* state) {
    // Decode AES key
    aran_xor_chain_decode(_GENESIS_PROD_AES_KEY, state->aes_key, 
                          sizeof(_GENESIS_PROD_AES_KEY), 92);
    
    // Decode HMAC secret
    aran_xor_chain_decode(_GENESIS_PROD_HMAC_SECRET, state->hmac_secret,
                          sizeof(_GENESIS_PROD_HMAC_SECRET), 62);
    
    // Decode pins
    aran_xor_chain_decode(_GENESIS_PROD_PIN0, state->tls_pin0,
                          sizeof(_GENESIS_PROD_PIN0), 113);
    aran_xor_chain_decode(_GENESIS_PROD_PIN1, state->tls_pin1,
                          sizeof(_GENESIS_PROD_PIN1), 141);
    
    // Decode salt
    aran_xor_chain_decode(_GENESIS_PROD_SALT, state->blinding_salt,
                          sizeof(_GENESIS_PROD_SALT), 195);
    
    // Decode endpoints
    aran_xor_chain_decode(_GENESIS_PROD_ENDPOINT, (volatile uint8_t*)state->sync_endpoint,
                          sizeof(_GENESIS_PROD_ENDPOINT), 43);
    aran_xor_chain_decode(_GENESIS_PROD_LICENSE_EP, (volatile uint8_t*)state->license_endpoint,
                          sizeof(_GENESIS_PROD_LICENSE_EP), 148);
    
    state->sync_interval_seconds = _GENESIS_PROD_SYNC_INTERVAL;
    state->default_reaction_policy = _GENESIS_PROD_REACTION_POLICY;
}

#endif // ARAN_GENESIS_PROD_H
