// Copyright 2024-2026 Mazhai Technologies
// Licensed under the Apache License, Version 2.0

#ifndef AranGenesis_h
#define AranGenesis_h

#include <stdint.h>
#include <stddef.h>

// ============================================================================
// Genesis Anchor — White-Box Obfuscated Fallback Configuration
//
// The Genesis state is the SDK's cryptographic root of trust. It contains
// encrypted fallback values for: AES-256 E2EE key, HMAC-SHA256 secret,
// blinded TLS pin hashes, default reaction policy, and sync endpoint.
//
// Storage: XOR-chain + bitwise rotation obfuscation. No plaintext in binary.
// Lifecycle: Decoded at runtime → sealed to Secure Enclave → wiped from RAM.
//
// Production builds: encoded blobs generated by build/encode_genesis.py
// Development builds: encoded at first-run from known dev values.
// ============================================================================

#define ARAN_GENESIS_AES_KEY_LEN     32
#define ARAN_GENESIS_HMAC_SECRET_LEN 32
#define ARAN_GENESIS_PIN_LEN         32
#define ARAN_GENESIS_SALT_LEN        16
#define ARAN_GENESIS_ENDPOINT_LEN    256
#define ARAN_GENESIS_PIN_COUNT       2

typedef struct {
    uint8_t  aes_key[ARAN_GENESIS_AES_KEY_LEN];
    uint8_t  hmac_secret[ARAN_GENESIS_HMAC_SECRET_LEN];
    uint8_t  tls_pins_blinded[ARAN_GENESIS_PIN_COUNT][ARAN_GENESIS_PIN_LEN];
    uint8_t  blinding_salt[ARAN_GENESIS_SALT_LEN];
    uint8_t  default_reaction_policy;   // ReactionPolicy enum (3 = KILL_APP)
    uint32_t config_version;
    uint32_t sync_interval_seconds;
    char     sync_endpoint[ARAN_GENESIS_ENDPOINT_LEN];
    char     license_endpoint[ARAN_GENESIS_ENDPOINT_LEN];
} AranGenesisState;

#ifdef __cplusplus
extern "C" {
#endif

/// Decode the XOR-chain obfuscated Genesis state and return it.
/// Caller MUST call aran_wipe_genesis_state() after sealing to Secure Enclave.
AranGenesisState aran_load_genesis_state(void);

/// Cryptographically wipe a genesis state from RAM (volatile memset).
void aran_wipe_genesis_state(AranGenesisState* state);

/// Update the dynamic TLS pin blinded hashes from Phantom Channel payload.
/// Called after a successful QUIC sync with mazhai-central.
void aran_genesis_update_dynamic_pins(
    const uint8_t* pin0_blinded, uint32_t pin0_len,
    const uint8_t* pin1_blinded, uint32_t pin1_len
);

/// Returns 1 if dynamic pins have been loaded from Phantom Channel, 0 if using Genesis fallback.
int aran_genesis_has_dynamic_pins(void);

#ifdef __cplusplus
}
#endif

#endif /* AranGenesis_h */
