// Copyright 2024-2026 Mazhai Technologies
// Licensed under the Apache License, Version 2.0
//
// Genesis Anchor — White-Box C Core
//
// XOR-chain + bitwise rotation obfuscation prevents:
// 1. Static binary string scanning (no plaintext keys in .rodata)
// 2. Simple XOR key recovery (chaining makes each byte depend on previous)
// 3. Parallel decryption (sequential dependency chain)
// 4. RAM dumping (volatile wipe after Secure Enclave seal)
//
// Production: encoded blobs generated by build/encode_genesis.py
// Development: runtime-encoded from known dev values on first call.

#include "AranGenesis.h"
#include <string.h>
#include <stdint.h>

// ============================================================================
// MARK: - XOR-Chain Obfuscation Engine
// ============================================================================

#define _GENESIS_SEED        0xA7u
#define _GENESIS_FK_AES      0x5Cu
#define _GENESIS_FK_HMAC     0x3Eu
#define _GENESIS_FK_PIN0     0x71u
#define _GENESIS_FK_PIN1     0x8Du
#define _GENESIS_FK_SALT     0xC3u
#define _GENESIS_FK_ENDPOINT 0x2Bu
#define _GENESIS_FK_LICENSE  0x94u

// Rotate left 8-bit
static inline uint8_t _rol8(uint8_t val, uint8_t n) {
    return (uint8_t)((val << n) | (val >> (8u - n)));
}

// XOR-chain encode: encoded[0] = plain[0] ^ (SEED ^ field_key)
// encoded[i] = plain[i] ^ ROL8(encoded[i-1], 3) ^ (i * 0x37) ^ field_key
static void _aran_xor_chain_encode(
    const uint8_t* __restrict plain,
    uint8_t* __restrict encoded,
    size_t len,
    uint8_t field_key
) {
    if (len == 0) return;
    encoded[0] = plain[0] ^ (_GENESIS_SEED ^ field_key);
    for (size_t i = 1; i < len; i++) {
        uint8_t rotated = _rol8(encoded[i - 1], 3);
        encoded[i] = plain[i] ^ rotated ^ ((uint8_t)(i * 0x37u)) ^ field_key;
    }
}

// XOR-chain decode (inverse of encode)
// Uses volatile pointers to prevent compiler from optimizing away intermediate values
static void _aran_xor_chain_decode(
    const uint8_t* __restrict encoded,
    volatile uint8_t* __restrict decoded,
    size_t len,
    uint8_t field_key
) {
    if (len == 0) return;
    decoded[0] = encoded[0] ^ (_GENESIS_SEED ^ field_key);
    for (size_t i = 1; i < len; i++) {
        uint8_t rotated = _rol8(encoded[i - 1], 3);
        decoded[i] = encoded[i] ^ rotated ^ ((uint8_t)(i * 0x37u)) ^ field_key;
    }
}

// ============================================================================
// MARK: - Dynamic Pin State (updated by Phantom Channel)
// ============================================================================

static volatile int _dynamic_pins_loaded = 0;
static uint8_t _dynamic_pin0_blinded[ARAN_GENESIS_PIN_LEN];
static uint8_t _dynamic_pin1_blinded[ARAN_GENESIS_PIN_LEN];

void aran_genesis_update_dynamic_pins(
    const uint8_t* pin0_blinded, uint32_t pin0_len,
    const uint8_t* pin1_blinded, uint32_t pin1_len
) {
    if (pin0_len > ARAN_GENESIS_PIN_LEN) pin0_len = ARAN_GENESIS_PIN_LEN;
    if (pin1_len > ARAN_GENESIS_PIN_LEN) pin1_len = ARAN_GENESIS_PIN_LEN;
    memcpy(_dynamic_pin0_blinded, pin0_blinded, pin0_len);
    memcpy(_dynamic_pin1_blinded, pin1_blinded, pin1_len);
    _dynamic_pins_loaded = 1;
}

int aran_genesis_has_dynamic_pins(void) {
    return _dynamic_pins_loaded;
}

// ============================================================================
// MARK: - Development Fallback Values
// ============================================================================
//
// In DEBUG builds, plaintext dev values are XOR-chain encoded at first call.
// In RELEASE builds, these are replaced by pre-computed const blobs from
// the build pipeline (build/encode_genesis.py).
//
// Dev AES key:     32 bytes of 0x00 (base64 "AAAA...=")
// Dev HMAC secret: repeating {0x04, 0x10, 0x41} pattern (base64 "BBBB...")
// Dev TLS pins:    SHA-256 of placeholder cert pins
// Dev blinding salt: 16 bytes of 0x42
// Dev endpoint:    "https://api.aran.mazhai.org"
// Dev license ep:  "https://api.aran.mazhai.org/api/v1/license/validate"

// Pre-encoded storage (initialized once)
static volatile int _genesis_encoded = 0;
static uint8_t _enc_aes_key[ARAN_GENESIS_AES_KEY_LEN];
static uint8_t _enc_hmac_secret[ARAN_GENESIS_HMAC_SECRET_LEN];
static uint8_t _enc_pin0[ARAN_GENESIS_PIN_LEN];
static uint8_t _enc_pin1[ARAN_GENESIS_PIN_LEN];
static uint8_t _enc_salt[ARAN_GENESIS_SALT_LEN];
static uint8_t _enc_endpoint[ARAN_GENESIS_ENDPOINT_LEN];
static uint8_t _enc_license_ep[ARAN_GENESIS_ENDPOINT_LEN];
static size_t  _enc_endpoint_len = 0;
static size_t  _enc_license_ep_len = 0;

// HMAC-SHA256 blinding of a TLS pin hash (using CC_SHA256 as HMAC approximation)
// In production, use a proper HMAC. Here we use H(salt || pin) for the C layer.
#include <CommonCrypto/CommonDigest.h>

static void _blind_pin_hash(
    const uint8_t* pin_sha256,
    const uint8_t* salt, size_t salt_len,
    uint8_t* blinded_out
) {
    CC_SHA256_CTX ctx;
    CC_SHA256_Init(&ctx);
    CC_SHA256_Update(&ctx, salt, (CC_LONG)salt_len);
    CC_SHA256_Update(&ctx, pin_sha256, CC_SHA256_DIGEST_LENGTH);
    CC_SHA256_Final(blinded_out, &ctx);
}

static void _aran_encode_dev_genesis(void) {
    if (_genesis_encoded) return;

    // --- Dev AES key: 32 zero bytes ---
    uint8_t dev_aes[ARAN_GENESIS_AES_KEY_LEN];
    memset(dev_aes, 0x00, sizeof(dev_aes));
    _aran_xor_chain_encode(dev_aes, _enc_aes_key, sizeof(dev_aes), _GENESIS_FK_AES);
    volatile uint8_t *p = (volatile uint8_t*)dev_aes;
    for (size_t i = 0; i < sizeof(dev_aes); i++) p[i] = 0;

    // --- Dev HMAC secret: repeating {0x04, 0x10, 0x41} pattern ---
    uint8_t dev_hmac[ARAN_GENESIS_HMAC_SECRET_LEN];
    for (size_t i = 0; i < sizeof(dev_hmac); i++) {
        static const uint8_t pattern[] = {0x04, 0x10, 0x41};
        dev_hmac[i] = pattern[i % 3];
    }
    _aran_xor_chain_encode(dev_hmac, _enc_hmac_secret, sizeof(dev_hmac), _GENESIS_FK_HMAC);
    p = (volatile uint8_t*)dev_hmac;
    for (size_t i = 0; i < sizeof(dev_hmac); i++) p[i] = 0;

    // --- Dev blinding salt: 16 bytes of 0x42 ---
    uint8_t dev_salt[ARAN_GENESIS_SALT_LEN];
    memset(dev_salt, 0x42, sizeof(dev_salt));
    _aran_xor_chain_encode(dev_salt, _enc_salt, sizeof(dev_salt), _GENESIS_FK_SALT);

    // --- Dev TLS pin hashes (SHA-256 of the placeholder base64 pin strings) ---
    // pin0 = SHA256("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=")
    // pin1 = SHA256("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=")
    {
        const char* pin0_str = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
        const char* pin1_str = "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=";
        uint8_t pin0_sha[CC_SHA256_DIGEST_LENGTH];
        uint8_t pin1_sha[CC_SHA256_DIGEST_LENGTH];
        CC_SHA256(pin0_str, (CC_LONG)strlen(pin0_str), pin0_sha);
        CC_SHA256(pin1_str, (CC_LONG)strlen(pin1_str), pin1_sha);

        // Blind with salt: H(salt || pin_hash)
        uint8_t pin0_blinded[ARAN_GENESIS_PIN_LEN];
        uint8_t pin1_blinded[ARAN_GENESIS_PIN_LEN];
        _blind_pin_hash(pin0_sha, dev_salt, sizeof(dev_salt), pin0_blinded);
        _blind_pin_hash(pin1_sha, dev_salt, sizeof(dev_salt), pin1_blinded);

        _aran_xor_chain_encode(pin0_blinded, _enc_pin0, ARAN_GENESIS_PIN_LEN, _GENESIS_FK_PIN0);
        _aran_xor_chain_encode(pin1_blinded, _enc_pin1, ARAN_GENESIS_PIN_LEN, _GENESIS_FK_PIN1);

        // Wipe intermediates
        p = (volatile uint8_t*)pin0_sha; for (size_t i = 0; i < 32; i++) p[i] = 0;
        p = (volatile uint8_t*)pin1_sha; for (size_t i = 0; i < 32; i++) p[i] = 0;
        p = (volatile uint8_t*)pin0_blinded; for (size_t i = 0; i < 32; i++) p[i] = 0;
        p = (volatile uint8_t*)pin1_blinded; for (size_t i = 0; i < 32; i++) p[i] = 0;
    }

    // Wipe salt plaintext
    p = (volatile uint8_t*)dev_salt;
    for (size_t i = 0; i < sizeof(dev_salt); i++) p[i] = 0;

    // --- Sync endpoint ---
    const char* ep = "https://api.aran.mazhai.org";
    size_t ep_len = strnlen(ep, ARAN_GENESIS_ENDPOINT_LEN - 1);
    uint8_t ep_buf[ARAN_GENESIS_ENDPOINT_LEN];
    memset(ep_buf, 0, sizeof(ep_buf));
    memcpy(ep_buf, ep, ep_len);
    _aran_xor_chain_encode(ep_buf, _enc_endpoint, ep_len + 1, _GENESIS_FK_ENDPOINT);
    _enc_endpoint_len = ep_len + 1;
    p = (volatile uint8_t*)ep_buf;
    for (size_t i = 0; i < sizeof(ep_buf); i++) p[i] = 0;

    // --- License endpoint ---
    const char* lep = "https://api.aran.mazhai.org/api/v1/license/validate";
    size_t lep_len = strnlen(lep, ARAN_GENESIS_ENDPOINT_LEN - 1);
    uint8_t lep_buf[ARAN_GENESIS_ENDPOINT_LEN];
    memset(lep_buf, 0, sizeof(lep_buf));
    memcpy(lep_buf, lep, lep_len);
    _aran_xor_chain_encode(lep_buf, _enc_license_ep, lep_len + 1, _GENESIS_FK_LICENSE);
    _enc_license_ep_len = lep_len + 1;
    p = (volatile uint8_t*)lep_buf;
    for (size_t i = 0; i < sizeof(lep_buf); i++) p[i] = 0;

    _genesis_encoded = 1;
}

// ============================================================================
// MARK: - Public API
// ============================================================================

AranGenesisState aran_load_genesis_state(void) {
    _aran_encode_dev_genesis();

    AranGenesisState state;
    memset(&state, 0, sizeof(state));

    // Decode each field from its XOR-chain encoded storage
    _aran_xor_chain_decode(_enc_aes_key, (volatile uint8_t*)state.aes_key,
                           ARAN_GENESIS_AES_KEY_LEN, _GENESIS_FK_AES);

    _aran_xor_chain_decode(_enc_hmac_secret, (volatile uint8_t*)state.hmac_secret,
                           ARAN_GENESIS_HMAC_SECRET_LEN, _GENESIS_FK_HMAC);

    _aran_xor_chain_decode(_enc_salt, (volatile uint8_t*)state.blinding_salt,
                           ARAN_GENESIS_SALT_LEN, _GENESIS_FK_SALT);

    // TLS pins: use dynamic if available, otherwise decode Genesis fallback
    if (_dynamic_pins_loaded) {
        memcpy(state.tls_pins_blinded[0], _dynamic_pin0_blinded, ARAN_GENESIS_PIN_LEN);
        memcpy(state.tls_pins_blinded[1], _dynamic_pin1_blinded, ARAN_GENESIS_PIN_LEN);
    } else {
        _aran_xor_chain_decode(_enc_pin0, (volatile uint8_t*)state.tls_pins_blinded[0],
                               ARAN_GENESIS_PIN_LEN, _GENESIS_FK_PIN0);
        _aran_xor_chain_decode(_enc_pin1, (volatile uint8_t*)state.tls_pins_blinded[1],
                               ARAN_GENESIS_PIN_LEN, _GENESIS_FK_PIN1);
    }

    // Decode sync endpoint
    if (_enc_endpoint_len > 0 && _enc_endpoint_len <= ARAN_GENESIS_ENDPOINT_LEN) {
        volatile uint8_t temp[ARAN_GENESIS_ENDPOINT_LEN];
        memset((void*)temp, 0, sizeof(temp));
        _aran_xor_chain_decode(_enc_endpoint, temp, _enc_endpoint_len, _GENESIS_FK_ENDPOINT);
        memcpy(state.sync_endpoint, (const void*)temp, _enc_endpoint_len);
        for (size_t i = 0; i < sizeof(temp); i++) temp[i] = 0;
    }

    // Decode license endpoint
    if (_enc_license_ep_len > 0 && _enc_license_ep_len <= ARAN_GENESIS_ENDPOINT_LEN) {
        volatile uint8_t temp[ARAN_GENESIS_ENDPOINT_LEN];
        memset((void*)temp, 0, sizeof(temp));
        _aran_xor_chain_decode(_enc_license_ep, temp, _enc_license_ep_len, _GENESIS_FK_LICENSE);
        memcpy(state.license_endpoint, (const void*)temp, _enc_license_ep_len);
        for (size_t i = 0; i < sizeof(temp); i++) temp[i] = 0;
    }

    // Static config values
    state.default_reaction_policy = 3; // KILL_APP
    state.config_version = 1;
    state.sync_interval_seconds = 60;

    return state;
}

void aran_wipe_genesis_state(AranGenesisState* state) {
    if (!state) return;
    // Volatile memset to prevent compiler dead-store elimination
    volatile uint8_t* p = (volatile uint8_t*)state;
    for (size_t i = 0; i < sizeof(AranGenesisState); i++) {
        p[i] = 0;
    }
}
